name: Update Docs Changelog

on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"

jobs:
  update-docs-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Simple test
        run: |
          echo "=== SIMPLE TEST ==="
          pwd
          ls -la
          echo "Current repo contents:"
          ls -la
          echo "CHANGELOG.md contents (first 10 lines):"
          head -10 CHANGELOG.md
          echo "Test completed successfully"
