name: Update Docs Changelog

on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"

jobs:
  update-docs-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SDK repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./sdk

      - name: Checkout docs portal repo
        uses: actions/checkout@v4
        with:
          repository: bobinstein/mock-docs-portal
          token: ${{ secrets.DOCS_PORTAL_TOKEN }}
          path: ./docs-portal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Debug initial directory structure
        run: |
          echo "=== INITIAL DIRECTORY STRUCTURE ==="
          pwd
          echo "--- ROOT CONTENTS ---"
          ls -la
          echo "--- SDK REPO CONTENTS ---"
          ls -la ./sdk/
          echo "--- DOCS PORTAL CONTENTS ---"
          ls -la ./docs-portal/
          echo "--- GITHUB DIRECTORY ---"
          ls -la .github/
          echo "--- WORKFLOWS DIRECTORY ---"
          ls -la .github/workflows/

      - name: Install dependencies
        run: |
          echo "=== INSTALLING DEPENDENCIES ==="
          pwd
          echo "--- CHANGING TO WORKFLOWS DIR ---"
          cd ${{ github.workspace }}/.github/workflows
          pwd
          echo "--- WORKFLOWS DIR CONTENTS ---"
          ls -la
          echo "--- INSTALLING NPM PACKAGES ---"
          npm install @octokit/rest simple-git axios
          echo "--- NODE_MODULES CREATED ---"
          ls -la

      - name: Update release notes
        run: |
          echo "=== UPDATING RELEASE NOTES ==="
          pwd
          echo "--- CHANGING TO WORKFLOWS DIR ---"
          cd ${{ github.workspace }}/.github/workflows
          pwd
          echo "--- WORKFLOWS DIR CONTENTS ---"
          ls -la
          echo "--- RUNNING SCRIPT ---"
          node update-release-notes.js
        env:
          SDK_CHANGELOG_PATH: ${{ github.workspace }}/sdk/CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.DOCS_PORTAL_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Push to docs portal repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOCS_PORTAL_TOKEN }}
        with:
          source_file: "./docs-portal/release-notes.md"
          destination_repo: "bobinstein/mock-docs-portal"
          destination_folder: "."
          user_email: "github-actions[bot]@users.noreply.github.com"
          user_name: "GitHub Actions Bot"
          commit_message: "chore: update changelog from SDK repo"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DOCS_PORTAL_TOKEN }}
          path: ./docs-portal
          commit-message: "chore: update changelog from SDK repo"
          title: "📝 Update changelog from SDK repo"
          body: |
            This PR updates the release notes with the latest changelog from the SDK repository.

            **Changes:**
            - Updated release notes with latest SDK changelog
            - Auto-generated by GitHub Actions workflow

            **Triggered by:** SDK repo commit to main branch
          branch: update-changelog
          delete-branch: true
