name: Update Docs Changelog

on:
  push:
    branches:
      - main
    paths:
      - "CHANGELOG.md"

jobs:
  update-docs-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Checkout docs portal repo
        uses: actions/checkout@v4
        with:
          repository: bobinstein/mock-docs-portal
          token: ${{ secrets.DOCS_PORTAL_TOKEN }}
          path: ./docs-portal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Debug directory structure
        run: |
          echo "=== DIRECTORY STRUCTURE ==="
          pwd
          echo "--- CURRENT REPO CONTENTS ---"
          ls -la
          echo "--- DOCS PORTAL CONTENTS ---"
          ls -la ./docs-portal/
          echo "--- WORKFLOWS DIRECTORY ---"
          ls -la .github/workflows/

      - name: Install dependencies
        run: |
          echo "=== INSTALLING DEPENDENCIES ==="
          pwd
          echo "--- CHECKING PACKAGE.JSON ---"
          cat package.json
          echo "--- INSTALLING NPM PACKAGES ---"
          echo "Starting npm install at $(date)"
          npm install
          echo "npm install completed at $(date)"
          echo "--- NODE_MODULES CREATED ---"
          ls -la node_modules/ | head -10

      - name: Test script execution
        run: |
          echo "=== TESTING SCRIPT EXECUTION ==="
          pwd
          echo "--- CHECKING SCRIPT EXISTS ---"
          ls -la .github/workflows/update-release-notes.js
          echo "--- CHECKING ENVIRONMENT VARIABLES ---"
          echo "SDK_CHANGELOG_PATH: $SDK_CHANGELOG_PATH"
          echo "GITHUB_TOKEN: ${GITHUB_TOKEN:0:10}..." 
          echo "SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL:-'NOT SET'}"
          echo "--- RUNNING SCRIPT TEST ---"
          echo "Starting script at $(date)"
          node .github/workflows/update-release-notes.js
          echo "Script completed at $(date)"
        env:
          SDK_CHANGELOG_PATH: ${{ github.workspace }}/CHANGELOG.md
          GITHUB_TOKEN: ${{ secrets.DOCS_PORTAL_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL || '' }}

      - name: Commit and push to docs portal
        run: |
          echo "=== COMMITTING AND PUSHING CHANGES ==="
          cd ./docs-portal
          pwd
          ls -la
          echo "--- GIT STATUS ---"
          git status
          echo "--- ADDING CHANGES ---"
          git add .
          echo "--- COMMITTING CHANGES ---"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions Bot"
          git commit -m "chore: update release notes from SDK changelog"
          echo "--- CREATING NEW BRANCH ---"
          git checkout -b update-changelog-$(date +%s)
          echo "--- PUSHING TO ORIGIN ---"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_PORTAL_TOKEN }}

      - name: Create Pull Request
        run: |
          echo "=== CREATING PULL REQUEST ==="
          cd ./docs-portal
          pwd
          echo "--- GETTING BRANCH NAME ---"
          BRANCH_NAME=$(git branch --show-current)
          echo "Current branch: $BRANCH_NAME"
          echo "--- CREATING PR VIA GITHUB API ---"
          curl -X POST \
            -H "Authorization: token ${{ secrets.DOCS_PORTAL_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/bobinstein/mock-docs-portal/pulls \
            -d '{
              "title": "📝 Update release notes from SDK changelog",
              "body": "This PR updates the release notes with the latest changelog from the SDK repository.\n\n**Changes:**\n- Updated release notes with latest SDK changelog\n- Auto-generated by GitHub Actions workflow\n\n**Triggered by:** SDK repo commit to main branch",
              "head": "'$BRANCH_NAME'",
              "base": "main"
            }'
        env:
          GITHUB_TOKEN: ${{ secrets.DOCS_PORTAL_TOKEN }}
